[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/campusconnect-backend-1.0.0.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
JAVA_VERSION = "21"
MAVEN_VERSION = "3.9.6"
